# Generated by Django 3.0 on 2021-08-19 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('form', models.CharField(choices=[('Tablet', 'Tablet'), ('Powder', 'Powder'), ('Liquid', 'Liquid'), ('Injection', 'Injection')], max_length=10)),
                ('is_in_morning', models.BooleanField(default=False)),
                ('is_in_afternoon', models.BooleanField(default=False)),
                ('is_in_evening', models.BooleanField(default=False)),
                ('morning_time', models.CharField(blank=True, choices=[('BB', 'Before Breakfast'), ('AB', 'After Breakfast')], max_length=2)),
                ('afternoon_time', models.CharField(blank=True, choices=[('BL', 'Before Lunch'), ('AL', 'After Lunch')], max_length=2)),
                ('evening_time', models.CharField(blank=True, choices=[('BD', 'Before Dinner'), ('AD', 'After Dinner'), ('BS', 'Before Sleep')], max_length=2)),
                ('morning_quantity', models.CharField(blank=True, max_length=5)),
                ('afternoon_quantity', models.CharField(blank=True, max_length=5)),
                ('evening_quantity', models.CharField(blank=True, max_length=5)),
                ('instructions', models.CharField(blank=True, max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_number', models.IntegerField(default=1, null=True)),
                ('name', models.CharField(max_length=100)),
                ('morning_time', models.CharField(blank=True, choices=[('BB', 'Before Breakfast'), ('AB', 'After Breakfast')], max_length=2)),
                ('afternoon_time', models.CharField(blank=True, choices=[('BL', 'Before Lunch'), ('AL', 'After Lunch')], max_length=2)),
                ('evening_time', models.CharField(blank=True, choices=[('BD', 'Before Dinner'), ('AD', 'After Dinner'), ('BS', 'Before Sleep')], max_length=2)),
                ('morning_quantity', models.CharField(blank=True, max_length=5)),
                ('afternoon_quantity', models.CharField(blank=True, max_length=5)),
                ('evening_quantity', models.CharField(blank=True, max_length=5)),
                ('no_of_days', models.CharField(blank=True, max_length=10)),
                ('instructions', models.CharField(blank=True, max_length=100)),
                ('date_prescribed', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Patient')),
            ],
        ),
    ]
